from __future__ import annotations

POLICY_CHUNKS: list[dict[str, str]] = [
    {"doc_id": "policy-r1", "source": "policy", "section": "R1", "text": "R1. Verify before you block on a weak signal. If the case rests on a single signal (including a risk score alone) and your assessed fraud probability is below 0.70, recommend VERIFY_WITH_CUSTOMER or STEP_UP_AUTH before any block. Blocking a legitimate customer on one signal is a policy breach."},
    {"doc_id": "policy-r2", "source": "policy", "section": "R2", "text": "R2. Customer denies the transaction. Recommend BLOCK_CARD and CREATE_CASE. Add FILE_REPORT if exposure exceeds $1,000 or the case connects to a shared device profile or another card's fraud."},
    {"doc_id": "policy-r3", "source": "policy", "section": "R3", "text": "R3. Customer confirms the transaction. Recommend CLOSE_NO_FRAUD. Note the confirmation in the case file."},
    {"doc_id": "policy-r4", "source": "policy", "section": "R4", "text": "R4. No reply within 24 hours. Recommend MONITOR_CARD and DECLINE_TRANSACTION for pending authorizations. Escalate if exposure exceeds $500."},
    {"doc_id": "policy-r5", "source": "policy", "section": "R5", "text": "R5. Card testing. Three or more small online authorizations on one card within an hour, followed by a larger purchase: recommend DECLINE_TRANSACTION and STEP_UP_AUTH. If a purchase over $100 has already cleared, recommend BLOCK_CARD."},
    {"doc_id": "policy-r6", "source": "policy", "section": "R6", "text": "R6. Shared origin. When several cards show fraud from the same device profile, the same billing region, or the same recipient email in one window, name the shared element, recommend CREATE_CASE and FILE_REPORT, and MONITOR_CONNECTED_CARDS for every card that shares it."},
    {"doc_id": "policy-r7", "source": "policy", "section": "R7", "text": "R7. Disputed but legitimate. When the customer disputes a charge that matches their own recurring pattern (same merchant, same amount, monthly), recommend CREATE_CASE, VERIFY_WITH_CUSTOMER, and WARN_CUSTOMER. Do not block."},
    {"doc_id": "policy-r8", "source": "policy", "section": "R8", "text": "R8. Escalate when uncertain and exposed. If the verdict is uncertain and exposure exceeds $500, or the evidence conflicts, recommend ESCALATE_TO_ANALYST."},
    {"doc_id": "policy-r9", "source": "policy", "section": "R9", "text": "R9. Undocumented patterns. When activity fits none of the known patterns but the evidence shows coordinated or repeated abuse across customers, recommend CREATE_CASE, FILE_REPORT, and ESCALATE_TO_ANALYST, and describe the pattern in your own words. Do not force it into a known category."},
    {"doc_id": "policy-r10", "source": "policy", "section": "R10", "text": "R10. Never BLOCK_ALL_CARDS unless at least two of the customer's cards show confirmed fraud or the customer's credentials are confirmed compromised."},
    {"doc_id": "policy-case-vs-report", "source": "policy", "section": "3a", "text": "A case (CREATE_CASE) is the bank's internal record of an investigation. Open one whenever fraud probability reaches 0.30, whenever you request evidence, or whenever a customer disputes a charge. A suspicious activity report (FILE_REPORT) is a regulatory filing sent outside the bank. File one when fraud is confirmed or strongly suspected and at least one of: exposure exceeds $1,000; the activity connects to a shared device profile, a shared region cluster, or another customer's fraud; the pattern is coordinated or undocumented (R9)."},
    {"doc_id": "pattern-card-testing", "source": "pattern", "section": "1", "text": "Card testing. A stolen card number is checked before use: three or more tiny online authorizations, often under $5, then a larger purchase. Confirmed by the sequence itself. Policy R5."},
    {"doc_id": "pattern-cnp-fraud", "source": "pattern", "section": "2", "text": "Card-not-present fraud. The number is used online without the card. Amounts and products that don't fit the cardholder's history, often in a burst of two to four within 48 hours. On its own, one unusual online purchase is ambiguous: verify. Policy R1 to R4."},
    {"doc_id": "pattern-cnp-new-device", "source": "pattern", "section": "3", "text": "Card-not-present fraud from a new device. Same as above, with the identity record marking the device as New for this account, sometimes behind a proxy. Stronger than pattern 2, still not proof: people buy new phones."},
    {"doc_id": "pattern-out-of-region", "source": "pattern", "section": "4", "text": "Out-of-region use. Card-present purchases in a billing region the cardholder has no history in, while their normal activity continues at home. Several days of purchases in one new region is a trip, not a clone. Policy R2, R3."},
    {"doc_id": "pattern-account-takeover", "source": "pattern", "section": "5", "text": "Account takeover. Mixed-channel activity inconsistent with the cardholder, often with device and match-flag anomalies, pointing to stolen credentials rather than a stolen number."},
]
